### ISSUE TITLE
Microphone to Midi / or Apple Music/Spotify integration

### ISSUE THREAD

**Issue by yosun** [aa221/Semantic-Manipulation-of-Music#1]
This is fascinating to experiment with in the larger population - except most people have their music collection in the cloud using Apple Music or Spotify. Maybe there is a way to route it thru microphone to midi to use your pipeline - better yet, please integrate Apple Music or Spotify APIs.

**Comment by aa221** [comment]
Thank you for submitting this and sorry for getting back to you quite late. I will definitely extend this so that it can take music through your microphone. The issue with Apple Music or Spotify APIs is that they do not provide you with the actual audio data needed for this experiment. Spotify used to provide demo urls which showed you a song snippet of 30 seconds, though I do not think this is the case anymore. In any case, the next iteration will focus on more sophisticated music transformations, though I will add realtime music uploading (via mic).
